function createaxes(Parent1, XData1, YData1, X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEAXES(PARENT1, XDATA1, YDATA1, X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  PARENT1:  axes parent
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 03-Apr-2017 13:31:29

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',0.6,'LineStyle','--',...
    'Color',[0.6 0.6 0.6]);

% Create plot
plot(X1,Y1,'DisplayName','UV\_CAST',...
    'MarkerFaceColor',[0.0784313753247261 0.168627455830574 0.549019634723663],...
    'Marker','diamond');

% Create plot
plot(X2,Y2,'DisplayName','DV\_CAST',...
    'MarkerFaceColor',[0.850980401039124 0.325490206480026 0.0980392172932625],...
    'Marker','pentagram');

% Create plot
plot(X3,Y3,'DisplayName','ABSM',...
    'MarkerFaceColor',[0.749019622802734 0 0.749019622802734],...
    'Marker','hexagram',...
    'Color',[1 0 1]);

% Create plot
plot(X4,Y4,'DisplayName','flooding',...
    'MarkerFaceColor',[0.494117647409439 0.184313729405403 0.556862771511078],...
    'Marker','>');

% Create xlabel
xlabel('Nodes density(V/km2)');

% Create ylabel
ylabel('Delay (s)');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 160]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 10]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Layer','top');
